### PR TITLE
chore: replace recommonmark with myst-parser

### PR DESCRIPTION
**Pull request by afuetterer**
[myst-parser](https://myst-parser.readthedocs.io/en/latest/) is the recommended way to use markdown in sphinx projects nowadays.

This PR replaces recommonmark with myst-parser and fixes the used rst specific markdown in the docs.

### CODE REVIEW

**Comment by afuetterer** [comment]
What do you think @MyPyDavid @jochenklar?
Merge or close?

**Comment by jochenklar** [comment]
I like it! @triole did the markdown transition back then, any objections?

**Comment by triole** [comment]
Not at all. Good to merge.

**Comment by afuetterer** [comment]
Excellent.

**Pull request merged**
